apiVersion: v1
kind: Service
metadata:
  labels:
    app: instavote
    component: queue
  name: redis
  namespace: instavote
spec:
  ports:
  - name: "redis"
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: instavote
    component: queue
  type: ClusterIP
