apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: instavote
    component: worker
  name: worker
  namespace: instavote
  annotations:
    kubernetes.io/change-cause: "Initial worker deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: instavote
      component: worker
  strategy: {}
  template:
    metadata:
      labels:
        app: instavote
        component: worker
    spec:
      containers:
      - image: schoolofdevops/worker:latest
        name: worker
        resources: {}
